<a href="https://colab.research.google.com/github/lubaochuan/ml_python/blob/main/chapter1_assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Machine Learning Workflow Assignment

**Textbook:** Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow (3rd ed.)  
**Purpose:** Reinforce core concepts from Chapter 1

---
### Student Information
- **Name:**  
- **Date:**  


## 1️⃣ Setup & Reproducibility

We begin by importing libraries and fixing a random seed to ensure reproducibility.


In [4]:
import numpy as np
import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

np.random.seed(42)

print("NumPy version:", np.__version__)
print("scikit-learn version:", sklearn.__version__)

NumPy version: 2.0.2
scikit-learn version: 1.6.1


## 2️⃣ Dataset: Features and Labels

We model whether a student **passes an exam** based on the number of **hours studied**.


In [11]:
# Feature: hours studied
X = np.array([1, 2, 3, 4, 5, 6]).reshape(-1, 1)

# Label: 0 = fail, 1 = pass
y = np.array([0, 0, 0, 1, 1, 1])

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


### ✍️ Concept Check 1

**Which best describes `X` and `y`?**

a) `X` is the label, `y` is the feature  
b) `X` and `y` are both labels  
c) `X` is the feature and `y` is the label  
d) Neither is used for training  

👉 **Your answer:**  


## 3️⃣ Train / Test Split

We split data so we can evaluate how well the model performs on **unseen data**.


In [6]:
X_train = X[:4]
X_test  = X[4:]

y_train = y[:4]
y_test  = y[4:]

### ✍️ Concept Check 2

**Why do we split data into training and test sets?**

a) To make training faster  
b) To remove noise  
c) To measure generalization to unseen data  
d) To reduce memory usage  

👉 **Your answer:**  


## 4️⃣ Training a Machine Learning Model

We now train a logistic regression classifier.


In [7]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

### ✍️ Concept Check 3

**Which line of code actually performs learning?**

a) `model = LogisticRegression()`  
b) `model.fit(X_train, y_train)`  
c) `model.predict(X_test)`  
d) `import sklearn`  

👉 **Your answer:**  


## 5️⃣ Making Predictions

In [8]:
predictions = model.predict(X_test)
predictions

array([1, 1])

In [9]:
y_test

array([1, 1])

## 6️⃣ Model Evaluation

In [10]:
accuracy = accuracy_score(y_test, predictions)
accuracy

1.0

### ✍️ Concept Check 4

**What does this accuracy value represent?**

a) How complex the model is  
b) The fraction of correct predictions on the test set  
c) The number of features  
d) How fast the model trained  

👉 **Your answer:**  


## 7️⃣ Overfitting (Conceptual)

Consider a model that memorizes the training data but fails on new examples.


### ✍️ Concept Check 5

**What does overfitting mean?**

a) The model is too slow  
b) The model predicts randomly  
c) The model memorizes training data but generalizes poorly  
d) The model has too few parameters  

👉 **Your answer:**  


## 8️⃣ Reflection Questions

Answer in **complete sentences**.


### 📝 Reflection 1  
**In your own words, what is a machine learning model?**

Your answer here:


### 📝 Reflection 2  
**Why is accuracy sometimes not enough to evaluate a model?**

Your answer here:


### 📝 Reflection 3  
**What might happen if we evaluated the model only on training data?**

Your answer here:


### 📝 Reflection 4  
**How does this notebook reflect the ML workflow described in Chapter 1?**

Your answer here:


## 9️⃣ Optional Challenge

Suppose this data came from a different school with different study habits.

**What risk does this pose to the model?**

☐ Data leakage  
☐ Overfitting  
☐ Lack of generalization  
☐ Feature scaling  

👉 **Correct choice:**  
